version: '3'
services:
  redis:
    image: redis:latest
    container_name: togglr-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
  postgres:
    image: postgres:13
    container_name: togglr-postgres
    environment:
      POSTGRES_DB: togglr
      POSTGRES_USER: togglr
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
volumes:
  redis-data:
  postgres-data:
